accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000aunit"]
  - name: bob
    coins: ["5000000000000aunit"]
validator:
  name: alice
  staked: "100000000000000000000aunit"
faucet:
  name: bob 
  coins: ["10aunit"]
build:
  binary: "treasurenetd"
init:
  home: "$HOME/.treasurenetd"
  app:
    json-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "treasurenet_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "aunit"
    mint:
      params:
        mint_denom: "aunit"
    crisis:
      constant_fee:
        denom: "aunit"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aunit"
    evm:
      params:
        evm_denom: "aunit"
