version: "3"

services:
  treasurenetdnode0:
    container_name: treasurenetdnode0
    image: "treasurenetd/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-treasurenetd.log}
    volumes:
      - /data/localnet-setup/node0/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode1:
    container_name: treasurenetdnode1
    image: "treasurenetd/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-treasurenetd.log}
    volumes:
      - /data/localnet-setup/node1/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode2:
    container_name: treasurenetdnode2
    image: "treasurenetd/node"
    environment:
      - ID=2
      - LOG=${LOG:-treasurenetd.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - /data/localnet-setup/node2/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode3:
    container_name: treasurenetdnode3
    image: "treasurenetd/node"
    environment:
      - ID=3
      - LOG=${LOG:-treasurenetd.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - /data/localnet-setup/node3/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode4:
    container_name: treasurenetdnode4
    image: "treasurenetd/node"
    ports:
      - "26661:26657"
      - "8585:8545"
      - "8586:8546"
      - "8129:8125"
    environment:
      - ID=4
      - LOG=${LOG:-treasurenetd.log}
    volumes:
      - /data/localnet-setup/node4/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode5:
    container_name: treasurenetdnode5
    image: "treasurenetd/node"
    ports:
      - "26662:26657"
      - "8595:8545"
      - "8596:8546"
      - "8130:8125"
    environment:
      - ID=5
      - LOG=${LOG:-treasurenetd.log}
    volumes:
      - /data/localnet-setup/node5/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode6:
    container_name: treasurenetdnode6
    image: "treasurenetd/node"
    environment:
      - ID=6
      - LOG=${LOG:-treasurenetd.log}
    ports:
      - "26663:26657"
      - "8605:8545"
      - "8606:8546"
      - "8131:8125"
    volumes:
      - /data/localnet-setup/node6/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode7:
    container_name: treasurenetdnode7
    image: "treasurenetd/node"
    environment:
      - ID=7
      - LOG=${LOG:-treasurenetd.log}
    ports:
      - "26664:26657"
      - "8615:8545"
      - "8616:8546"
      - "8132:8125"
    volumes:
      - /data/localnet-setup/node7/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
